#!/usr/bin/env bash
commitMessage=$1

if [ ! $# == 1 ]
    then
    echo "There should a commit message for this publishing of material."
    exit 1
fi

npm install

cd ~/Codez/adron.github.io/_working/
wintersmith build

# For OS-X
cp -r build/ ../../adron.github.io/

# For Linux
#cp -a build/. ../../adron.github.io/
rm -rf build

cd ~/Codez/adron.github.io/

git add -A
git commit -m "$commitMessage"
git push origin master
