#!/usr/bin/env bash
commitMessage=$1

# Fix this sometime.
# if [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
#     echo "Come on now, you got fixins to do before you go screwing up everything using Windows."
# fi


if [ ! $# == 1 ]
    then
    echo "There should a commit message for this publishing of material."
    exit 1
fi

npm install

cd ~/Codez/adron.github.io/_working/

wintersmith build

# For OS-X
if [ "$(uname)" == "Darwin" ]; then
    cp -r build/ ../../adron.github.io/
# For Linux
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    cp -a build/. ../../adron.github.io/
fi

rm -rf build

cd ~/Codez/adron.github.io/

git add -A
git commit -m "$commitMessage"
git push origin master
