#!/usr/bin/env bash
commitMessage=$1

if [ ! $# == 1 ]
    then
    echo "There should a commit message for this publishing of material."
    exit 1
fi

npm install

cd ~/Codez/adron.github.io/_working/
wintersmith build

# For OS-X
if [ "$(uname)" == "Darwin" ]; then
    cp -r build/ ../../adron.github.io/
# For Linux
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    cp -a build/. ../../adron.github.io/
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    echo "WTF ARE YOU DOING, STOP IT!"
fi

rm -rf build

cd ~/Codez/adron.github.io/

git add -A
git commit -m "$commitMessage"
git push origin master
