#!/usr/bin/env bash

# Just a title
talktitle=$1
confname=$2
# Format 2013-04-30
published=`date +%Y-%m-%d:%H:%M:%S`
author='Adron Hall'

if [ ! $# == 2 ]
    then
    echo "There should be at least the title of the talk and of the conference."
    exit 1
fi

cd contents/talks

echo "Changed into talks directory. Creating $talktitle."

mkdir "$talktitle"
cd "$talktitle"

# Takes out the dashes. Still needs title cased.
cleanedTitle=${talktitle//[-]/' '}

cat <<EOT >> index.md
---
title: $cleanedTitle
author: $author
date: $published
template: talk.jade
---
## $cleanedTitle
### *@ $confname by $author*
EOT