#!/usr/bin/env bash

cd contents/articles

echo "Moved into articles path."

# Just a title
blogtitle=$1
blogdate=$(date "+%Y-%m-%d-%H:%M:%S")

if [ ! $# == 1 ]
  then
    echo "Needs a blog entry title."
    exit 1
fi

echo "Creating $blogtitle."
mkdir "$blogtitle"
cd "$blogtitle"

# Takes out the dashes. Still needs title cased.
cleanedTitle=${blogtitle//[-]/' '}

cat <<EOT >> index.md
---
title: $cleanedTitle
author: Adron Hall
date: $blogdate
template: article.jade
---
<span class="more"></span>

<div class="image float-right">
    ![Streamsets](streamset2.jpg)
</div>
EOT

echo "All done!"
