#!/usr/bin/env bash

cd contents/articles

echo "Moved into articles path."

# Just a title
blogtitle=$1
# Format 2013-04-30
blogdate=$2

if [ ! $# == 2 ]
    then
    echo "There should be two arguments."
    exit 1
fi

echo "Creating $blogtitle."
mkdir "$blogtitle"
cd "$blogtitle"

# Takes out the dashes. Still needs title cased.
cleanedTitle=${blogtitle//[-]/' '}

cat <<EOT >> index.md
---
title: $cleanedTitle
author: Adron Hall
date: $blogdate
template: article.jade
---
<img class="img-responsive" src="./elasticon-tour-2015-in-seattle/streamset3.jpg" />

<div class="image float-right">
    ![Streamsets](streamset2.jpg)
</div>

<span class="more"></span>

EOT

echo "All done!"